### PR TITLE
Building out a first minimal version of search functionality

### PR DESCRIPTION
**Pull request by keenon**

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
I think I have found a few things:

- The list of public datasets on my profile is empty, but I have two public folders. The public folders are called "Folder" and "Folder3". If I go to any other profile (including yours and Jenn's, which have public datasets in the search page), there are no public datasets either.
- My two public folders are not in the list of published folders in search either. If I check "Include Unpublished", the only two datasets appearing with my name are "Test" (which is a subject, not a folder, and takes me to the subject view) and "/private", which takes me to /data/<UUID>/private, which does not exist (I think it is getting confused with the private folder in /data/private). This looks like an Index with a missing +1 or -1 somewhere.

**Comment by AlbertoCasasOrtiz** [comment]
Everything looks better now! Now I can see the public folders and the public datasets appear in the profile. Only a few comments, maybe some of them are intended behavior:

- If I click on "show unpublished", my private folder and the subject (Called Test) are still appearing.
- If I publish a folder, I have to refresh for it to appear in search.
- I cannot search the Home folders by name (I put home or any other word in the title of home datasets in the search bar and nothing appear)
- Search is only looking for coincidences in title, not in description.
- In profile, public datasets occupy the full width.

**Comment by keenon** [comment]
Ok, many of these should be address:

- Fixed: If I click on "show unpublished", my private folder and the subject (Called Test) are still appearing.
- Fixed: If I publish a folder, I have to refresh for it to appear in search.
- Fixed: In profile, public datasets occupy the full width.

For these last two, I'm going to make a new ticket. I think we have to do something clever with empty files to allow the frontend to download everything it needs to know in order to do these searches without having to download hundreds of JSON files every page refresh.

- I cannot search the Home folders by name (I put home or any other word in the title of home datasets in the search bar and nothing appear)
- Search is only looking for coincidences in title, not in description.

**Comment by keenon** [comment]
Here's the ticket for richer searches: https://github.com/keenon/AddBiomechanics/issues/59

**Comment by AlbertoCasasOrtiz** [comment]
This is looking better. I tested and everything is working properly. Then only thing is that my Subject (Test) is still appearing in the search. This is the link to the subject: http://localhost:3000/data/207f3d89-0057-4907-a24b-39bea906ef42/Test/

**Comment by AlbertoCasasOrtiz** [comment]
I just found another error while testing a different thing. I was trying to edit my information in my profile, and when I try to modify any value I got the "Network error. We got an error trying to upload your data!" popup.

**Comment by AlbertoCasasOrtiz** [comment]
Everything looks good now, no bugs found. Merging!

**Comment by AlbertoCasasOrtiz** [comment]
Just added space between badges in search results for aesthetics.

**Pull request merged**
