### PR TITLE
Adding backend CI testing

### PR DESCRIPTION
**Pull request by nickbianco**
Addresses #294 by adding a basic continuous integration testing suite basic on existing tests under `server/engine`. This can be expanded to include more backend tests (e.g., tests for `mocap_server.py`), and possibly unittests for the frontend.

Summary of minor changes:
- Upgraded `numpy` version in the requirements to be compatible with the latest OpenSim conda package on Linux.
- Refactored `test_subject.py` and `test_trial.py` so that all test files are found relative to the file locations automatically.
- Commented out some failing tests (@keenon, maybe you could take a look at these?).
- Renamed the out-dated `test_engine.py` to `old_test_engine.py` so it is ignored by `unittest` on CI.

### CODE REVIEW

**Comment by keenon** [comment]
Oh this is so exciting! Nice :D

When these tests pass consider this approved!

**Comment by nickbianco** [comment]
@keenon, do you have any thoughts on the two failing tests I commented out?

**Comment by keenon** [comment]
Nothing obvious stands out to me, but I'm on a work binge trying to get the next big step change improvement in AddBiomechanics output data quality, so I'll make sure I get to these tests as I update the engine code to incorporate the other new changes over the next few days. For now, let's just merge this as is, and I'll make sure I update all the tests with the big new PR that'll be landing soon.

**Review by keenon — APPROVED** [review]
LGTM, let's merge it!

**Pull request merged**
