### PR TITLE
Update logos and theme colors

### PR DESCRIPTION
**Pull request by aymanhab**
Update artwork to latest logos

### CODE REVIEW

**Comment by aymanhab** [comment]
@jenhicks or @keenon please check the diffs when you have a chance and let me know if adjustments are needed. Thank you

**Comment by jenhicks** [comment]
Thanks @aymanhab !  We're not incorporating the AddBiomechanics logotype anywhere (the styled AddBiomechanics text). I circled some places where this would show up. 
Screen Shot 2022-11-17 at 3 48 42 PM
Screen Shot 2022-11-17 at 3 49 26 PM

Then there were some new colors that David suggested for the buttons. I don't see these in the Files Changed. 

It looks like you may have changed the colors in the arrows of the logo instead? Those are OK to stay the same as the colors in the PDF I shared. Just the button colors would change.

@keenon Input on this from you is also very welcome, of course!

**Comment by aymanhab** [comment]
Thanks for the feedback @jenhicks I updated the images to match the pdf you sent me while matching the size of the original images. Not sure how we build the PR into a full site to view all the affected pages. The text/buttons/links use a different mechanism (css files AFAICT), but there're multiple css files in the repo, I made multiple changes locally but I'd like to hear from @keenon about which colors/files he uses to control the color/theme before proceeding. The colors suggested by Jen for reference are:
2C579E -> 44, 87, 158 dark-blue for buttons
4a71b3 -> 74, 113, 179 darker-blue for hover state

**Comment by keenon** [comment]
I believe it's defined here: https://github.com/keenon/AddBiomechanics/blob/main/frontend/src/scss/config/variables.scss. I used a starter project from the Bootstrap store to define the UI, so I'm not precisely sure. I think the variable you're mostly interested in is $primary, and I'm not sure where mouse hover is defined globally. At the end of the day, if it looks good on your local copy, I think that's good enough :)

**Comment by aymanhab** [comment]
Here're the latest screenshots, I can only run front end so I'm a bit limited on what I can test/capture:
Screenshot 2022-11-29 140349
Screenshot 2022-11-29 140307

**Comment by jenhicks** [comment]
Thanks @aymanhab ... did you update the colors to the codes noted above? The log in and create new buttons are showing up as purple. The all white version of the logo also isn't looking great. I would use the version of the logo that is meant for a dark background directly. I can also help with exporting logos in the correct sizes and formats (in illustrator) if you give me the specs.

**Comment by aymanhab** [comment]
OK @jenhicks there supposed to be one place to change primary color (as theme-color) and all other colors are generated/updated based on it. That didn't work everywhere so I changed another place, now this is how it looks:
Screenshot 2022-11-30 112452

**Comment by aymanhab** [comment]
The file logo-login.svg used to have transparent arrows, not clear how to do that in the tool I'm using "inkscape", here is the new file:
logo-login

**Comment by jenhicks** [comment]
@aymanhab Could you share the various file sizes that you need for the logo mark and whether it is displayed on a dark or light background? We don't need to reproduce that exact transparency. It also looks like there may be some issues with the file conversions you did, since you don't have illustrator.

And for the text that I circled in my earlier comment (where the name AddBiomechanics appears), is it possible to replace this with an image that has the styled logo font? If you gave specs for this, could also help generate the necessary files.

I'll be in the office today if it's easier to chat in person.

**Comment by aymanhab** [comment]
Hi Jen,

I'm on the way in, better to chat in person so we're in sync.

**Comment by aymanhab** [comment]
@jenhicks Here's the latest login screen based on our discussion yesterday
Screenshot 2022-12-02 105112

**Comment by aymanhab** [comment]
And here's the svg with matched text but without changing colors, please let me know if you want the text colors changed as well. 
logo-with-text2

**Comment by jenhicks** [comment]
Thanks @aymanhab ... the login screen looks good to me!

The font looks off in the second image (it got compressed). The circle part also shouldn't have that gray circle in the background. And the colors should be the light blue and black as in the PDF (the page with the white background).

**Comment by jenhicks** [comment]
Apologies .. I am seeing now the issue with the gray circle in the background for most of the logo images.

**Comment by aymanhab** [comment]
@jenhicks I didn't change the font, just copied it from the file you sent, the likely issue is that the text was stretched/scaled to match size. Anyway, here's another take with colors that work on white background
logo-with-text2

**Comment by aymanhab** [comment]
Or maybe I should I remove the circle altogether?

**Comment by aymanhab** [comment]
> @aymanhab I'm also trying to put some of these logos on the Mobilize site, so feel free to ping me if there is anything I can try to do and help.

Thanks @mattpetrucci once we figure out what to do with the gray circle we'll be close to done here and then you can use the logos everywhere

**Comment by jenhicks** [comment]
Confirming that none of the logos should have the gray circle @aymanhab

**Comment by jenhicks** [comment]
Thanks @aymanhab ... these all look good to me now as far as the file versions.

**Comment by jenhicks** [comment]
@keenon Do you have any feedback?

**Comment by keenon** [comment]
This generally looks good to me. I think a serif font for the logo text is going to require cascading changes to the design, since we use san-serifs everywhere else. I feel like serif's in general need to be handled with extreme care - they either look great (e.g. Medium, NYT, etc), or more often they look dated and 90s. I think this usage feels a bit dated to me, but I'm not a good enough designer to know exactly why. San-serif is much more forgiving. Are there any san-serif font options for the logo text?

**Comment by jenhicks** [comment]
@keenon I don't think we'd change all the fonts on the website. Only when it is used as a logo. Could someone share a screenshot of how the serif looks in practice when used just in the top left on the page?

**Comment by jenhicks** [comment]
I'm having trouble seeing your screenshot upload @aymanhab

**Comment by aymanhab** [comment]
Retrying...
Screenshot 2022-12-02 160204

**Comment by jenhicks** [comment]
Thanks @aymanhab! I think that looks OK, but also fine with using sans serif, if that's your preference @keenon 

With the OpenCap logo, I believe we are using Century Gothic

**Comment by aymanhab** [comment]
Merging per verbal approval in dev meeting, thanks @jenhicks for the review

**Pull request merged**
